---
log_level: 'debug' # chose 'info' or 'debug'
debug_console_interval: 0.01

nucleo_port: '/dev/ttyACM_f446re'
nucleo_baud: 115200

odrive_port: '/dev/ttyACM_odrive'
odrive_baud: 115200
odrive_speed_lim: 40000.0
odrive_current_lim: 70.0
